<?php
$data = array (
  15 => 
  array (
    'cat_id' => '15',
    'cat_name' => '白酒',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '8',
    'sort_order' => '20',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '15',
    'name' => '白酒',
  ),
  93 => 
  array (
    'cat_id' => '93',
    'cat_name' => '馥郁香型',
    'measure_unit' => '',
    'parent_id' => '15',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '8',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '93',
    'name' => '馥郁香型',
  ),
  83 => 
  array (
    'cat_id' => '83',
    'cat_name' => '酱香型',
    'measure_unit' => '',
    'parent_id' => '15',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '8',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '64',
    'level' => 1,
    'id' => '83',
    'name' => '酱香型',
  ),
  87 => 
  array (
    'cat_id' => '87',
    'cat_name' => '浓香型',
    'measure_unit' => '',
    'parent_id' => '15',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '8',
    'sort_order' => '51',
    'has_children' => '0',
    'goods_num' => '11',
    'level' => 1,
    'id' => '87',
    'name' => '浓香型',
  ),
  16 => 
  array (
    'cat_id' => '16',
    'cat_name' => '葡萄酒',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '8',
    'sort_order' => '30',
    'has_children' => '8',
    'goods_num' => 0,
    'level' => 0,
    'id' => '16',
    'name' => '葡萄酒',
  ),
  99 => 
  array (
    'cat_id' => '99',
    'cat_name' => '香槟',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '8',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '99',
    'name' => '香槟',
  ),
  96 => 
  array (
    'cat_id' => '96',
    'cat_name' => '贵腐',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '8',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '96',
    'name' => '贵腐',
  ),
  97 => 
  array (
    'cat_id' => '97',
    'cat_name' => '冰酒',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '8',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '97',
    'name' => '冰酒',
  ),
  94 => 
  array (
    'cat_id' => '94',
    'cat_name' => '桃红葡萄酒',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '8',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '94',
    'name' => '桃红葡萄酒',
  ),
  95 => 
  array (
    'cat_id' => '95',
    'cat_name' => '起泡酒',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '8',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '95',
    'name' => '起泡酒',
  ),
  81 => 
  array (
    'cat_id' => '81',
    'cat_name' => '红葡萄酒',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '8',
    'sort_order' => '51',
    'has_children' => '0',
    'goods_num' => '54',
    'level' => 1,
    'id' => '81',
    'name' => '红葡萄酒',
  ),
  77 => 
  array (
    'cat_id' => '77',
    'cat_name' => '白葡萄酒',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '8',
    'sort_order' => '52',
    'has_children' => '0',
    'goods_num' => '229',
    'level' => 1,
    'id' => '77',
    'name' => '白葡萄酒',
  ),
  98 => 
  array (
    'cat_id' => '98',
    'cat_name' => '加强型葡萄酒',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '8',
    'sort_order' => '80',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '98',
    'name' => '加强型葡萄酒',
  ),
  17 => 
  array (
    'cat_id' => '17',
    'cat_name' => '洋酒',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '8',
    'sort_order' => '40',
    'has_children' => '10',
    'goods_num' => 0,
    'level' => 0,
    'id' => '17',
    'name' => '洋酒',
  ),
  76 => 
  array (
    'cat_id' => '76',
    'cat_name' => '白兰地',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '8',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '32',
    'level' => 1,
    'id' => '76',
    'name' => '白兰地',
  ),
  91 => 
  array (
    'cat_id' => '91',
    'cat_name' => '力娇酒',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '8',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '91',
    'level' => 1,
    'id' => '91',
    'name' => '力娇酒',
  ),
  86 => 
  array (
    'cat_id' => '86',
    'cat_name' => '金酒',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '8',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '362',
    'level' => 1,
    'id' => '86',
    'name' => '金酒',
  ),
  82 => 
  array (
    'cat_id' => '82',
    'cat_name' => '威末酒',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '8',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
    'level' => 1,
    'id' => '82',
    'name' => '威末酒',
  ),
  61 => 
  array (
    'cat_id' => '61',
    'cat_name' => '韩国烧酒',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '8',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '37',
    'level' => 1,
    'id' => '61',
    'name' => '韩国烧酒',
  ),
  80 => 
  array (
    'cat_id' => '80',
    'cat_name' => '伏特加',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '8',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '758',
    'level' => 1,
    'id' => '80',
    'name' => '伏特加',
  ),
  74 => 
  array (
    'cat_id' => '74',
    'cat_name' => '预调酒',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '8',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '25',
    'level' => 1,
    'id' => '74',
    'name' => '预调酒',
  ),
  90 => 
  array (
    'cat_id' => '90',
    'cat_name' => '朗姆酒',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '8',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '33',
    'level' => 1,
    'id' => '90',
    'name' => '朗姆酒',
  ),
  89 => 
  array (
    'cat_id' => '89',
    'cat_name' => '威士忌',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '8',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '26',
    'level' => 1,
    'id' => '89',
    'name' => '威士忌',
  ),
  85 => 
  array (
    'cat_id' => '85',
    'cat_name' => '龙舌兰',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '8',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '293',
    'level' => 1,
    'id' => '85',
    'name' => '龙舌兰',
  ),
  3 => 
  array (
    'cat_id' => '3',
    'cat_name' => '数字时代',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => '20',
    'level' => 0,
    'id' => '3',
    'name' => '数字时代',
  ),
  92 => 
  array (
    'cat_id' => '92',
    'cat_name' => '图书玩具',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '92',
    'name' => '图书玩具',
  ),
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '惠享生活',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '60',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '1',
    'name' => '惠享生活',
  ),
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => '餐饮美食',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '61',
    'has_children' => '0',
    'goods_num' => '12',
    'level' => 1,
    'id' => '2',
    'name' => '餐饮美食',
  ),
  13 => 
  array (
    'cat_id' => '13',
    'cat_name' => '休闲娱乐',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '63',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '13',
    'name' => '休闲娱乐',
  ),
  14 => 
  array (
    'cat_id' => '14',
    'cat_name' => '生活服务',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '65',
    'has_children' => '0',
    'goods_num' => '11',
    'level' => 1,
    'id' => '14',
    'name' => '生活服务',
  ),
);
?>