<?php
$data = array (
  0 => 
  array (
    'cat_id' => '15',
    'cat_name' => '白酒',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '8',
    'sort_order' => '20',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  1 => 
  array (
    'cat_id' => '16',
    'cat_name' => '葡萄酒',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '8',
    'sort_order' => '30',
    'has_children' => '8',
    'goods_num' => 0,
  ),
  2 => 
  array (
    'cat_id' => '17',
    'cat_name' => '洋酒',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '8',
    'sort_order' => '40',
    'has_children' => '10',
    'goods_num' => 0,
  ),
  3 => 
  array (
    'cat_id' => '3',
    'cat_name' => '数字时代',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => '20',
  ),
  4 => 
  array (
    'cat_id' => '1',
    'cat_name' => '惠享生活',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '60',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  5 => 
  array (
    'cat_id' => '2',
    'cat_name' => '餐饮美食',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '61',
    'has_children' => '0',
    'goods_num' => '12',
  ),
  6 => 
  array (
    'cat_id' => '13',
    'cat_name' => '休闲娱乐',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '63',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  7 => 
  array (
    'cat_id' => '14',
    'cat_name' => '生活服务',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '65',
    'has_children' => '0',
    'goods_num' => '11',
  ),
  8 => 
  array (
    'cat_id' => '92',
    'cat_name' => '图书玩具',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  9 => 
  array (
    'cat_id' => '93',
    'cat_name' => '馥郁香型',
    'measure_unit' => '',
    'parent_id' => '15',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '8',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  10 => 
  array (
    'cat_id' => '83',
    'cat_name' => '酱香型',
    'measure_unit' => '',
    'parent_id' => '15',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '8',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '64',
  ),
  11 => 
  array (
    'cat_id' => '87',
    'cat_name' => '浓香型',
    'measure_unit' => '',
    'parent_id' => '15',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '8',
    'sort_order' => '51',
    'has_children' => '0',
    'goods_num' => '11',
  ),
  12 => 
  array (
    'cat_id' => '99',
    'cat_name' => '香槟',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '8',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  13 => 
  array (
    'cat_id' => '96',
    'cat_name' => '贵腐',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '8',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  14 => 
  array (
    'cat_id' => '97',
    'cat_name' => '冰酒',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '8',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  15 => 
  array (
    'cat_id' => '94',
    'cat_name' => '桃红葡萄酒',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '8',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  16 => 
  array (
    'cat_id' => '95',
    'cat_name' => '起泡酒',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '8',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  17 => 
  array (
    'cat_id' => '81',
    'cat_name' => '红葡萄酒',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '8',
    'sort_order' => '51',
    'has_children' => '0',
    'goods_num' => '54',
  ),
  18 => 
  array (
    'cat_id' => '77',
    'cat_name' => '白葡萄酒',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '8',
    'sort_order' => '52',
    'has_children' => '0',
    'goods_num' => '229',
  ),
  19 => 
  array (
    'cat_id' => '98',
    'cat_name' => '加强型葡萄酒',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '8',
    'sort_order' => '80',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  20 => 
  array (
    'cat_id' => '76',
    'cat_name' => '白兰地',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '8',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '32',
  ),
  21 => 
  array (
    'cat_id' => '91',
    'cat_name' => '力娇酒',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '8',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '91',
  ),
  22 => 
  array (
    'cat_id' => '86',
    'cat_name' => '金酒',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '8',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '362',
  ),
  23 => 
  array (
    'cat_id' => '82',
    'cat_name' => '威末酒',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '8',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
  ),
  24 => 
  array (
    'cat_id' => '61',
    'cat_name' => '韩国烧酒',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '8',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '37',
  ),
  25 => 
  array (
    'cat_id' => '80',
    'cat_name' => '伏特加',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '8',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '758',
  ),
  26 => 
  array (
    'cat_id' => '74',
    'cat_name' => '预调酒',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '8',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '25',
  ),
  27 => 
  array (
    'cat_id' => '90',
    'cat_name' => '朗姆酒',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '8',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '33',
  ),
  28 => 
  array (
    'cat_id' => '89',
    'cat_name' => '威士忌',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '8',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '26',
  ),
  29 => 
  array (
    'cat_id' => '85',
    'cat_name' => '龙舌兰',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '8',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '293',
  ),
);
?>